name: Scrape and Update Tables

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '*/60 * * * *'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 pandas openpyxl pandas selenium webdriver-manager

    - name: Run script
      run: python program.py

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        if git status --porcelain | grep -q snam_table.xlsx; then
            git add snam_table.xlsx
            git commit -m 'Update tables'
            git push https://x-access-token:${GH_TOKEN}@github.com/nayan-khemka/extractdata.git
        fi
